/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fromscratch.users.infrastructure.jakartaee;

import static org.assertj.core.api.Assertions.assertThatCode;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import com.fromscratch.users.infrastructure.httpserver.HttpServerJUnitExtension;
import com.fromscratch.users.infrastructure.jakartaee.JakartaMvcBoot;


@DisplayName("Jakarta MVC Boot")
@ExtendWith(HttpServerJUnitExtension.class)
class JakartaMvcBootTest {
    

    @Test
    @DisplayName("should start and stop a Jakarta application")
    void shouldStartAndStopAJakartaApplication() {
        assertThatCode(JakartaMvcBoot::run).doesNotThrowAnyException();
        assertThatCode(JakartaMvcBoot::stop).doesNotThrowAnyException();
    }
}
